# Generated by Django 2.2.10 on 2020-02-14 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200213_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 12, 58, 58, 508265, tzinfo=utc)),
        ),
    ]
