# Generated by Django 2.2.10 on 2020-04-02 14:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200214_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 14, 23, 47, 509077, tzinfo=utc)),
        ),
    ]
