# Generated by Django 2.2.10 on 2020-04-06 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200406_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 12, 30, 27, 357390, tzinfo=utc)),
        ),
    ]
