# Generated by Django 2.2.10 on 2020-04-13 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200413_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 10, 23, 57, 411246, tzinfo=utc)),
        ),
    ]
