# Generated by Django 2.2.10 on 2020-04-06 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200402_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 11, 6, 27, 952231, tzinfo=utc)),
        ),
    ]
