# Generated by Django 2.2.10 on 2020-04-06 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200406_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 14, 21, 20, 789956, tzinfo=utc)),
        ),
    ]
