# Generated by Django 2.2.10 on 2020-04-13 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200406_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 10, 7, 37, 83030, tzinfo=utc)),
        ),
    ]
