# Generated by Django 2.2.10 on 2020-04-13 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200413_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 13, 35, 12, 510307, tzinfo=utc)),
        ),
    ]
