# Generated by Django 2.2.10 on 2020-04-13 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200413_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 13, 51, 58, 576178, tzinfo=utc)),
        ),
    ]
