# Generated by Django 2.2.10 on 2020-04-20 07:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200413_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 7, 56, 16, 475039, tzinfo=utc)),
        ),
    ]
